language: generic 
matrix:
  include:
    - os: linux
      sudo: required
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    - os: linux
      sudo: required
      env: COMPILER_NAME=gcc CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          packages:
            - g++-4.9
            - cmake
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
    - os: osx
      compiler: clang-3.8
      env: COMPILER=clang++ -std=c++11

  script:
  - cd $TRAVIS_BUILD_DIR
  # build the target. This will call haxe with the HXFLAGS and HXFLAGS_EXTRA environment variables
  - HXFLAGS="-cp src -main test.TestAll" ~/travis-hx/build.sh
  # run the tests
  - ~/travis-hx/runtests.sh $FILENAME # this will set the $FILENAME defined on the environment variable to run the tests

